name: "Hiero Solo Action"
description: "Run a Hiero-based network using the Task tool"
inputs:
  installMirrorNode:
    description: "Defines if a mirror node should be installed"
    required: true
    default: false
    type: boolean
  hederaVersion:
    description: "Version of Hedera to use. Defaults to Mainnet version."
    required: false
    default: "v0.52.2"
  mirrorNodePort:
    description: "Port for Mirror Node"
    required: false
    default: "8080"
  installRelay:
    description: "Install JSON-RPC-Relay"
    required: false
    default: false
    type: boolean
  relayPort:
    description: "Port for JSON-RPC-Relay"
    required: false
    default: "7546"
runs:
  using: "composite"
  steps:
    - name: Print inputs
      shell: bash
      run: |
        echo "installMirrorNode: ${{ inputs.installMirrorNode }}"
        echo "installRelay: ${{ inputs.installRelay }}"

    - name: Setup prerequisites
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y wget

    - name: Install Kind (Kubernetes in Docker)
      uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde
      with:
        version: v0.21.0
        kubectl_version: v1.28.6
        cluster_name: solo-network
        wait: 120s

    - name: Install Task tool
      shell: bash
      run: |
        curl -sSL https://taskfile.dev/install.sh | sh
        sudo mv ./task /usr/local/bin/

    - name: Clone Solo repository
      shell: bash
      run: git clone https://github.com/hashgraph/solo.git && cd solo

    - name: Install dependencies and build Solo
      shell: bash
      run: cd solo && task

    - name: Start Solo network
      shell: bash
      run: |
        cd solo
        if [ "${{ inputs.installRelay }}" == "true" ]; then
          task default-with-relay
        elif [ "${{ inputs.installMirrorNode }}" == "true" ]; then
          task default-with-mirror
        else
          task
        fi

    - name: Expose Hedera Explorer if Mirror Node or Relay is enabled
      if: ${{ inputs.installMirrorNode == 'true' || inputs.installRelay == 'true' }}
      shell: bash
      run: |
        echo "Hedera Explorer is available at http://localhost:8080"

    - name: Stop Solo network
      shell: bash
      run: cd solo && task clean

branding:
  icon: "share-2"
  color: "black"
