name: "Hiero Solo Action"
description: "Run a Hiero-based network by using the solo tool"
inputs:
  installMirrorNode:
    description: "Defines if a mirror node should be installed"
    required: true
    default: false
    type: boolean
  hederaVersion:
    description: "Version of Hedera to use. Defaults to Mainnet version."
    required: false
    default: "v0.58.1"
  mirrorNodePort:
    description: "Port for Mirror Node"
    required: false
    default: "8080"
  installRelay:
    description: "Install JSON-RPC-Relay"
    required: false
    default: false
    type: boolean
  relayPort:
    description: "Port for JSON-RPC-Relay"
    required: false
    default: "7546"
outputs:
  accountId:
    description: "Hedera account id for a new account"
    value: ${{ steps.create-account.outputs.accountId }}
  publicKey:
    description: "Hedera public key for the new account"
    value: ${{ steps.create-account.outputs.publicKey }}
  privateKey:
    description: "Hedera private key for the new account"
    value: ${{ steps.create-account.outputs.privateKey }}
runs:
  using: "composite"
  steps:
    - name: Print inputs
      shell: bash
      run: |
        echo "installMirrorNode: ${{ inputs.installMirrorNode }}"
        echo "is installMirrorNode: ${{ inputs.installMirrorNode == 'true' }}"

    - name: Setup Java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Node
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: 22

    - name: Install WGet CLI
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y wget

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Setup Helm
      uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
      with:
        version: "v3.12.3" # helm version

    - name: Setup Kind
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        install_only: true
        node_image: kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30
        version: v0.26.0
        kubectl_version: v1.31.4
        verbosity: 3
        wait: 120s

    - name: Install Solo
      shell: bash
      run: npm install -g @hashgraph/solo@0.35.1

    - name: Deploy Solo Test Network
      shell: bash
      run: |
        # Define environment variables
        export SOLO_CLUSTER_NAME=solo-cluster
        export SOLO_NAMESPACE=solo
        export SOLO_DEPLOYMENT=solo-deployment
        export SOLO_EMAIL=solo-action@hiero.org
        
        # Create Kind cluster
        kind create cluster -n "${SOLO_CLUSTER_NAME}"
        
        # Initialize solo and deploy network
        solo init
        solo deployment create --node-aliases node1 --namespace "${SOLO_NAMESPACE}" --context kind-${SOLO_CLUSTER_NAME} --email "${SOLO_EMAIL}" --deployment-clusters kind-${SOLO_CLUSTER_NAME} --deployment "${SOLO_DEPLOYMENT}"
        solo node keys --node-aliases node1 --gossip-keys --tls-keys --quiet-mode
        solo cluster setup --cluster-setup-namespace "${SOLO_CLUSTER_NAME}" --quiet-mode    
        solo network deploy --node-aliases node1 --deployment "${SOLO_DEPLOYMENT}"
        solo node setup --node-aliases node1 --deployment "${SOLO_DEPLOYMENT}"
        solo node start --node-aliases node1 --deployment "${SOLO_DEPLOYMENT}"

    - name: Verify Network Status
      shell: bash
      run: |
        echo "Checking network status..."
        kubectl get pods -n ${SOLO_NAMESPACE} --context kind-${SOLO_CLUSTER_NAME}
        solo network status --deployment ${SOLO_DEPLOYMENT} --context kind-${SOLO_CLUSTER_NAME} || { echo "Network status check failed"; exit 1; }

    - name: Create Account
      id: create-account
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        SOLO_NAMESPACE: solo
        SOLO_CLUSTER_NAME: solo-cluster
        SOLO_DEPLOYMENT: solo-deployment
      run: |
        # Debug: Verify cluster context and namespace
        echo "Current context: $(kubectl config current-context)"
        echo "Namespace: ${SOLO_NAMESPACE}"

        # Run solo account create and capture output
        echo "Running solo account create..."
        solo account create --context kind-${SOLO_CLUSTER_NAME} --namespace ${SOLO_NAMESPACE} > account_output.txt 2>&1 || {
          echo "solo account create failed with exit code $?"
          cat account_output.txt
          exit 1
        }
        echo "Raw output of solo account create:"
        cat account_output.txt

        # Process the output with the Python script
        JSON=$(cat account_output.txt | python3 $GITHUB_ACTION_PATH/extractAccountAsJson.py) || {
          echo "Failed to process solo account create output with extractAccountAsJson.py"
          exit 1
        }
        echo "Parsed JSON: $JSON"

        # Extract account details
        export HEDERA_ACCOUNT_ID=$(echo "$JSON" | jq -r '.accountId')
        export HEDERA_ACCOUNT_PUBLIC_KEY=$(echo "$JSON" | jq -r '.publicKey')

        # Debug: Check for secret existence
        echo "Checking for secret account-key-$HEDERA_ACCOUNT_ID in namespace ${SOLO_NAMESPACE}..."
        kubectl get secret -n ${SOLO_NAMESPACE} --context kind-${SOLO_CLUSTER_NAME} || echo "No secrets found in namespace ${SOLO_NAMESPACE}"
        kubectl get secret account-key-$HEDERA_ACCOUNT_ID -n ${SOLO_NAMESPACE} --context kind-${SOLO_CLUSTER_NAME} || echo "Secret account-key-$HEDERA_ACCOUNT_ID not found"

        # Extract private key from secret
        export HEDERA_ACCOUNT_PRIVATE_KEY=$(kubectl get secret account-key-$HEDERA_ACCOUNT_ID -n ${SOLO_NAMESPACE} --context kind-${SOLO_CLUSTER_NAME} -o jsonpath='{.data.privateKey}' | base64 -d | xargs) || {
          echo "Failed to retrieve private key for account $HEDERA_ACCOUNT_ID"
          exit 1
        }

        # Update account with HBAR
        solo account update --account-id $HEDERA_ACCOUNT_ID --hbar-amount 10000000 --context kind-${SOLO_CLUSTER_NAME} --namespace ${SOLO_NAMESPACE} || {
          echo "Failed to update account $HEDERA_ACCOUNT_ID"
          exit 1
        }

        # Log and set outputs
        echo "Account ID: $HEDERA_ACCOUNT_ID"
        echo "Public Key: $HEDERA_ACCOUNT_PUBLIC_KEY"
        echo "Private Key: $HEDERA_ACCOUNT_PRIVATE_KEY"
        echo "accountId=$HEDERA_ACCOUNT_ID" >> $GITHUB_OUTPUT
        echo "publicKey=$HEDERA_ACCOUNT_PUBLIC_KEY" >> $GITHUB_OUTPUT
        echo "privateKey=$HEDERA_ACCOUNT_PRIVATE_KEY" >> $GITHUB_OUTPUT

branding:
  icon: "share-2"
  color: "black"
