name: "Hiero Solo Action"
description: "Run a Hiero-based network using the solo tool"

inputs:
  installMirrorNode:
    description: "Defines if a mirror node should be installed"
    required: true
    default: false
    type: boolean
  installRelay:
    description: "Install JSON-RPC-Relay"
    required: false
    default: false
    type: boolean

outputs:
  accountId:
    description: "Hedera account ID for a new account"
    value: ${{ steps.create-account.outputs.accountId }}
  publicKey:
    description: "Hedera public key for the new account"
    value: ${{ steps.create-account.outputs.publicKey }}
  privateKey:
    description: "Hedera private key for the new account"
    value: ${{ steps.create-account.outputs.privateKey }}

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "21"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install Required CLI Tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget jq

    - name: Setup Kind
      uses: helm/kind-action@v1.12.0
      with:
        install_only: true
        node_image: kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30
        version: "v0.26.0"
        kubectl_version: "v1.31.4"
        verbosity: 3
        wait: "120s"

    - name: Install Task Tool
      shell: bash
      run: |
        sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

    - name: Clone Solo Repository and Install Dependencies
      shell: bash
      run: |
        git clone https://github.com/hashgraph/solo.git
        cd solo
        task

    - name: Start Solo Network
      shell: bash
      run: |
        cd solo
        if [ "${{ inputs.installRelay }}" == "true" ]; then
          task default-with-relay
        elif [ "${{ inputs.installMirrorNode }}" == "true" ]; then
          task default-with-mirror
        else
          task
        fi

    - name: Create Account
      id: create-account
      shell: bash
      run: |
        JSON=$(solo account create | jq -r '.')
        HEDERA_ACCOUNT_ID=$(echo "$JSON" | jq -r '.accountId')
        HEDERA_ACCOUNT_PUBLIC_KEY=$(echo "$JSON" | jq -r '.publicKey')
        HEDERA_ACCOUNT_PRIVATE_KEY=$(echo "$JSON" | jq -r '.privateKey')

        echo "accountId=$HEDERA_ACCOUNT_ID" >> "$GITHUB_OUTPUT"
        echo "publicKey=$HEDERA_ACCOUNT_PUBLIC_KEY" >> "$GITHUB_OUTPUT"
        echo "privateKey=$HEDERA_ACCOUNT_PRIVATE_KEY" >> "$GITHUB_OUTPUT"

branding:
  icon: "share-2"
  color: "black"
