name: Validate Hedera Solo Outputs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Checkout Repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Hedera Solo
        uses: ./
        id: solo

      - name: ✅ Validate Hedera Solo Outputs
        run: |
          if [ -z "${{ steps.solo.outputs.accountId }}" ]; then
            echo "❌ Error: accountId is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.privateKey }}" ]; then
            echo "❌ Error: privateKey is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.publicKey }}" ]; then
            echo "❌ Error: publicKey is missing!"
            exit 1
          fi
          echo "🎉 All outputs are valid!"
