name: JSON-RPC Relay CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: hashgraph/hedera-json-rpc-relay
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install Dependencies
        run: npm install

      - name: Build Relay
        run: npm run build

      - name: Start Relay Server
        run: |
          npm run start &
          sleep 5

      - name: Test Relay Connection
        run: |
          curl -v -X POST http://localhost:7546 \
            -H "Content-Type: application/json" \
            -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
