name: JSON-RPC Relay Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-json-rpc-relay:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Checkout Repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Hedera Solo with JSON-RPC Relay
        uses: ./
        with:
          installRelay: true
        id: solo

      - name: ✅ Validate Hedera Solo Outputs
        run: |
          if [ -z "${{ steps.solo.outputs.accountId }}" ]; then
            echo "❌ Error: accountId is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.privateKey }}" ]; then
            echo "❌ Error: privateKey is missing!"
            exit 1
          fi
          if [ -z "${{ steps.solo.outputs.publicKey }}" ]; then
            echo "❌ Error: publicKey is missing!"
            exit 1
          fi
          echo "🎉 All outputs are valid!"
          echo "Account ID: ${{ steps.solo.outputs.accountId }}"
          echo "Public Key: ${{ steps.solo.outputs.publicKey }}"
          echo "Private Key: ${{ steps.solo.outputs.privateKey }}"

      - name: ✅ Validate JSON-RPC Relay
        run: |
          # Wait for the JSON-RPC Relay to be fully up and running
          sleep 10

          # Send a JSON-RPC request to eth_chainId
          RESPONSE=$(curl -s -w "%{http_code}" -X POST 'http://localhost:7546' \
            -H 'Content-Type: application/json' \
            -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' \
            -o response.json)

          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ Error: JSON-RPC request failed with status code $RESPONSE"
            cat response.json
            exit 1
          fi

          # Check if the response contains a valid chainId
          CHAIN_ID=$(jq -r '.result' response.json)
          if [ -z "$CHAIN_ID" ] || [ "$CHAIN_ID" = "null" ]; then
            echo "❌ Error: Invalid or missing chainId in response"
            cat response.json
            exit 1
          fi

          echo "✅ JSON-RPC Relay request successful"
          echo "Chain ID: $CHAIN_ID"
          cat response.json
      
